### ISSUE TITLE
[suggestion] click through signs and frames

### ISSUE THREAD

**Issue by IFedor-F** [sisby-folk/swingthrough#1]
Add the opportunity to click through signs and frames to open chests, like in the mod clickthrough

**Comment by sleepingdragoninn** [comment]
any reason to not use clickthrough?

**Comment by IFedor-F** [comment]
The author does not update the mod xd

**Comment by sleepingdragoninn** [comment]
ClickThrough is MIT - if you're looking for it to work on 1.20, I'd recommend a PR'd fork or port instead!

**Comment by sleepingdragoninn** [comment]
(When we update our modpack to 1.20 in a few months, we'll likely want a version of ClickThrough. if it isn't ported then, we'll likely do it ourselves)

**Comment by IFedor-F** [comment]
Ok. thanks

**Comment by sleepingdragoninn** [comment]
https://modrinth.com/mod/clickthrough-continued

**Comment by IFedor-F** [comment]
thanks
